version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: 013-setup-feature-branch
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /
    target-branch: 013-setup-feature-branch
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
